<?php
/**
 * @file  Strategy Investors
 * @author Miguel Martínez <miguel01amd@gmail.com>
 * @package Corp - Sections
 * @info Display blocks with "Strategy Investors- Group Bimbo" information.
 * @vertion dev 1.0.0
 */

/**
 * Implement hook_block_info()
 */
function gbcStrategyInvestors_block_info() {
  $blocks = array();
  $blocks['block_gbcStrategyInvestors'] = array(
    'info'       => t('Strategy Investors'),
    'title'      => '<none>',
    'status'     => TRUE,
    'region'     => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages'      => 'investors/strategy-and-competitive-advantages',
  );

  return $blocks;
}

/**
 * Implement hook_block_view()
 */
function gbcStrategyInvestors_block_view($delta) {
  #$block = array();
  $block = [];
  switch ($delta) {
    case 'block_gbcStrategyInvestors':
      $block['content'] = _gbcStrategyInvestors_content();
  } // end switch
  return $block;
}

/**
 * Implement hook_theme()
 */
function gbcStrategyInvestors_theme() {
  $theme = array();
  $theme['gbcStrategyInvestors'] = array(
  'variables' => array(),
  'template' => 'templates/gbcStrategyInvestors',
  );
  return $theme;
}

/**
 * Retrive slider data and pass to homeslider template
 *
 * @return theme
 */
function _gbcStrategyInvestors_content() {
  $vid  = taxonomy_vocabulary_machine_name_load('strategy_and_competitive_advantages')->vid;
  $language = _gbcCommon_language();
  $content = [];

  $qry = db_select('taxonomy_term_data', 'ttd');
  $qry->leftJoin('field_data_field_class', 'fdfc', 'fdfc.entity_id = ttd.tid');
  $qry->leftJoin('field_data_field_link', 'flink', 'flink.entity_id = ttd.tid');
  $qry->condition('ttd.vid', $vid, '=');
  $qry->condition('ttd.language', $language, '=');
  $qry->fields('ttd', ['tid', 'name']);
  $qry->fields('fdfc', ['field_class_value']);
  $qry->fields('flink', ['field_link_value']);
  $qry->orderBy('ttd.weight', 'ASC');
  $results = $qry->execute()->fetchAll();

  if (!empty($results)) {
    foreach ($results as $term) {
      $content['data'][] = [
        'tid'   => $term->tid,
        'name'  => $term->name,
        'class'  => $term->field_class_value,
        'link'  => $term->field_link_value,
      ];
    }//endforeach
  }//endif
/**/
          #$rows['link'] = _gbcStrategyInvestors_about_menu('menu-about-investors');
          #watchdog('$rows[link]', print_r($rows['link'],TRUE));
/**/
  return theme('gbcStrategyInvestors', array('content' => $content));
}
