<?php

/**
 * Implements hook_block_info().
 */
function gbcFinancialInformation_block_info() {
  $blocks = [];
  $blocks['financialinfo_menu'] = array(
    'info'       => t('Block of Financial Information Menu'),
    'weight'     => 1,
    'status'     => TRUE,
    'region'     => 'content',
    'cache'      => DRUPAL_NO_CACHE,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages'      => 'inversionistas/informacion-financiera',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function gbcFinancialInformation_block_view($delta = '') {
  $block = [];
  switch ($delta) {
    case 'financialinfo_menu':
      $block['content'] = gbcFinancialInformation_get_content();
      break;
  }//end switch
  return $block;
}

/**
 * Implements hook_theme().
 */
function gbcFinancialInformation_theme() { 
  $theme = [];
  $theme['financialinfo_menu'] = [ 'template' => 'templates/financial-info',  ];

  return $theme;
}

/**
 * Return menu to Financial Info content
 * @return theme (array)
 */ 
function gbcFinancialInformation_get_content() {
  $content = [];
  $lang    = _gbcCommon_language();

  $qry = db_select('menu_links', 'mn');
  $qry->condition('mn.menu_name', 'menu-financial-information-menu', '=')
      ->condition('mn.language', $lang, '=');
  $qry->fields('mn', ['mlid', 'link_path', 'link_title', 'weight'])
      ->orderBy('mn.weight', 'ASC');
  $results = $qry->execute()->fetchAll();

  if ( !empty($results) ) {
    foreach ($results as $result) {  
      $link = l('<h6>'.$result->link_title.'</h6>', $result->link_path, array('html' => TRUE, 'attributes' => array('class' => 'btn-link')));

      $content[] = [
        'mlid' => $result->mlid,
        'link' => $link,
      ];
    }// endforeach
  }// endoif
 
  return theme('financialinfo_menu', array('content' => $content));
}

/**
 * Return items to vocabulary of quaterly
 * @return array 
 */ 
function gbcFinancialInformation_get_quarters() {
  $options = [];

  $lang  = _gbcCommon_language();
  $vocab = taxonomy_vocabulary_machine_name_load('quarterly');
  $vid   = $vocab->vid;

  $qry = db_select('taxonomy_term_data', 'ttd');
  $qry->condition('ttd.vid', $vid, '=')
      ->condition('ttd.language', $lang, '=');
  $qry->fields('ttd', ['tid', 'name'])
      ->orderBy('ttd.weight', 'ASC');
  $results = $qry->execute()->fetchAll();

  if (isset($results) && !empty($results)) {
    foreach ($results as $result) {  
      $options[$result->tid] = $result->name;
    }// endforeach
  }// endoif
  
  return $options;
}