<?php
/**
 * @file Home Focus Investors
 * @author Miguel Martínez <miguel01amd@gmail.com>
 * @package Corp - Sections
 * @info Display blocks with "Home Focus Investors- Group Bimbo" information.
 * @vertion dev 1.0.0
 */

/**
 * Implement hook_block_info()
 */
function gbcFocusInvestors_block_info() {
  $blocks = array();
  $blocks['block_gbcFocusInvestors'] = array(
    'info'       => t('Home Focus Investors '),
    'title'      => '<none>',
    'status'     => TRUE,
    'region'     => 'content',
    'weight'     => 2,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages'      => 'investors',
  );

  return $blocks;
}

/**
 * Implement hook_block_view()
 */
function gbcFocusInvestors_block_view($delta) {
  #$block = array();
  $block = [];
  switch ($delta) {
    case 'block_gbcFocusInvestors':
      $block['content'] = _gbcFocusInvestors_content();
  } // end switch
  return $block;
}

/**
 * Implement hook_theme()
 */
function gbcFocusInvestors_theme() {
  $theme = array();
  $theme['gbcFocusInvestors'] = array(
  'variables' => array(/*'menu_items' => array()*/),
  #'template' => 'homeslider',
  'template' => 'templates/gbcFocusInvestors',
  );
  return $theme;
}

/**
 * Retrive slider data and pass to homeslider template
 *
 * @return theme
 */
function _gbcFocusInvestors_content() {
  $content  = [];
  $language = _gbcCommon_language();

  $vocab  = taxonomy_vocabulary_machine_name_load('ri_investors_focus');
  $vid    = $vocab->vid;
  // Get data using current language
  $query = db_select('taxonomy_term_data', 'ttd');
  $query->leftJoin('field_data_field_focus_title', 'fdfft', 'fdfft.entity_id = ttd.tid');
  $terms = $query
          ->fields('ttd', ['tid', 'name', 'description'])
          ->fields('fdfft', array('field_focus_title_value'))
          ->condition('ttd.vid', $vid, '=')
          ->condition('ttd.language', $language, '=')
          #->condition('ttd.status', 1, '=')
          ->range(0,3)
          ->orderBy('ttd.weight')
          ->execute()
          ->fetchAll();

  if (count($terms)<=0) {
    return array();
  } // end if

  #$slider_content = array();

    foreach ($terms as $result) {

      $content['data'][] = array(
        'title' => $result->name,
        'name' => $result->field_focus_title_value,
        'description' => $result->description,
      );
    } // end foreach


  return theme('gbcFocusInvestors', array('content' => $content));
}
